CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Email] NVARCHAR(320) NOT NULL,
	[NotificationsEnabled] BIT NOT NULL DEFAULT 1,
	[UseFahrenheit] BIT NOT NULL DEFAULT 1,
    [Latitude] DECIMAL(3, 1) NOT NULL,
    [Longitude] DECIMAL(4, 1) NOT NULL,
	[UTCOffset] INT NOT NULL,
    [DateAdded] DATETIME NOT NULL DEFAULT GETUTCDATE()
)
